### PR TITLE
Latest substantive configuration changes from Andy

### PR DESCRIPTION
**Pull request by aidanheerdegen**
I've pulled out the substantive configuration changes from Andy's latest run config and attempted to document them as much as possible.

Maybe get @AndyHoggANU to take a look at them and make sure they are canonical. For example, are we still using riverspread options, or is the runoff being pre-spread in @nicjhan's MATM code?

### CODE REVIEW

**Comment by aekiss** [comment]
re. db46faca93cc34289b93fda611e2e8b0dad99552 - do riverspread options also need turning on with 1 deg and 0.1 deg?

**Comment by aekiss** [comment]
re. 6e6c03626b180a153163c84afe6897be1f634ffe - correction to comment - namelist items were added, not removed

**Comment by aekiss** [comment]
re. 1fcb04141789ce5d7fb974378c042548aa438b2c - correction to comment - ocean_month added, ocean_daily removed

**Comment by nicjhan** [comment]
I'm not sure that river spread is needed since this issue https://github.com/OceansAus/access-om2/issues/20

**Pull request merged**
